//
//  GenerateEmbeddedDTDs.swift
//  Pipeline Neo • https://github.com/TheAcharya/pipeline-neo
//  © 2026 • Licensed under MIT License
//
//  Generates EmbeddedDTDs.swift from Sources/PipelineNeo/FCPXML DTDs so the CLI
//  can run as a single binary without a resource bundle. Run from package root:
//  swift run GenerateEmbeddedDTDs  or  ./Scripts/generate_embedded_dtds.sh
//

import Foundation

@main
struct GenerateEmbeddedDTDs {
    /// Parses version from DTD filename (e.g. "Final_Cut_Pro_XML_DTD_version_1.10.dtd" → (1, 10)).
    private static func version(from dtdFileName: String) -> (major: Int, minor: Int)? {
        let prefix = "Final_Cut_Pro_XML_DTD_version_"
        let suffix = ".dtd"
        guard dtdFileName.hasPrefix(prefix), dtdFileName.hasSuffix(suffix) else { return nil }
        let middle = String(dtdFileName.dropFirst(prefix.count).dropLast(suffix.count))
        let parts = middle.split(separator: ".")
        guard parts.count == 2,
              let major = Int(parts[0]),
              let minor = Int(parts[1]) else { return nil }
        return (major, minor)
    }

    static func main() throws {
        let fileManager = FileManager.default
        let cwd = fileManager.currentDirectoryPath
        let dtdDir = (cwd as NSString).appendingPathComponent("Sources/PipelineNeo/FCPXML DTDs")
        let outDir = (cwd as NSString).appendingPathComponent("Sources/PipelineNeoCLI/Generated")
        let outPath = (outDir as NSString).appendingPathComponent("EmbeddedDTDs.swift")

        guard let contents = try? fileManager.contentsOfDirectory(atPath: dtdDir) else {
            fputs("Error: could not read DTD directory at \(dtdDir)\n", stderr)
            exit(1)
        }

        let dtdFiles = contents
            .filter { $0.hasSuffix(".dtd") }
            .sorted { a, b in
                guard let va = version(from: a), let vb = version(from: b) else {
                    return a < b
                }
                if va.major != vb.major { return va.major < vb.major }
                return va.minor < vb.minor
            }
        var entries: [String] = []

        for f in dtdFiles {
            let path = (dtdDir as NSString).appendingPathComponent(f)
            guard let data = fileManager.contents(atPath: path) else { continue }
            let name = (f as NSString).deletingPathExtension
            let b64 = data.base64EncodedString()
            entries.append("        \"\(name)\": Data(base64Encoded: \"\"\"\n\(b64)\n\"\"\")!")
        }

        try fileManager.createDirectory(atPath: outDir, withIntermediateDirectories: true)

        let header = """
        //
        //  EmbeddedDTDs.swift
        //  Pipeline Neo • https://github.com/TheAcharya/pipeline-neo
        //  © 2026 • Licensed under MIT License
        //
        //
        //\tGenerated by GenerateEmbeddedDTDs – do not edit by hand.
        //
        //

        import Foundation

        enum EmbeddedDTDs {
            /// Returns embedded DTD data for the given resource name (no .dtd extension).
            static func data(for name: String) -> Data? { table[name] }
            private static let table: [String: Data] = [
        """

        let footer = """
            ]
        }
        """

        let body = entries.joined(separator: ",\n")
        let output = header + body + "\n" + footer

        do {
            try output.write(toFile: outPath, atomically: true, encoding: .utf8)
            print("Wrote \(outPath) (\(entries.count) DTDs)")
        } catch {
            fputs("Error writing output: \(error)\n", stderr)
            exit(1)
        }
    }
}
