//
//  GenerateEmbeddedDTDs.swift
//  Pipeline Neo • https://github.com/TheAcharya/pipeline-neo
//  © 2026 • Licensed under MIT License
//
//  Generates EmbeddedDTDs.swift from FCPXML DTDs in this package.
//  Run from package root: swift run GenerateEmbeddedDTDs
//

import Foundation

@main
struct GenerateEmbeddedDTDs {
    static func main() throws {
        let fileManager = FileManager.default
        let cwd = fileManager.currentDirectoryPath
        let dtdDir = (cwd as NSString).appendingPathComponent("Sources/PipelineNeo/FCPXML DTDs")
        let outDir = (cwd as NSString).appendingPathComponent("Sources/PipelineNeoCLI/Generated")
        let outPath = (outDir as NSString).appendingPathComponent("EmbeddedDTDs.swift")

        guard let contents = try? fileManager.contentsOfDirectory(atPath: dtdDir) else {
            fputs("Error: could not read DTD directory at \(dtdDir)\n", stderr)
            exit(1)
        }

        let dtdFiles = contents.filter { $0.hasSuffix(".dtd") }.sorted()
        var entries: [String] = []

        for f in dtdFiles {
            let path = (dtdDir as NSString).appendingPathComponent(f)
            guard let data = fileManager.contents(atPath: path) else { continue }
            let name = (f as NSString).deletingPathExtension
            let b64 = data.base64EncodedString()
            entries.append("        \"\(name)\": Data(base64Encoded: \"\"\"\n\(b64)\n\"\"\")!")
        }

        try fileManager.createDirectory(atPath: outDir, withIntermediateDirectories: true)

        let header = """
        //
        //  EmbeddedDTDs.swift
        //  Pipeline Neo • https://github.com/TheAcharya/pipeline-neo
        //  © 2026 • Licensed under MIT License
        //
        //
        //\tGenerated by GenerateEmbeddedDTDs – do not edit by hand.
        //
        //

        import Foundation

        enum EmbeddedDTDs {
            /// Returns embedded DTD data for the given resource name (no .dtd extension).
            static func data(for name: String) -> Data? { table[name] }
            private static let table: [String: Data] = [
        """

        let footer = """
            ]
        }
        """

        let body = entries.joined(separator: ",\n")
        let output = header + body + "\n" + footer

        do {
            try output.write(toFile: outPath, atomically: true, encoding: .utf8)
            print("Wrote \(outPath) (\(entries.count) DTDs)")
        } catch {
            fputs("Error writing output: \(error)\n", stderr)
            exit(1)
        }
    }
}
